name: head
channels:
  - defaults
dependencies:
  - pip
  - pip:
    - botorch==0.8.5
    - matplotlib==3.7.1
    - openpyxl==3.1.2
    - pandas==2.0.3
    - seaborn==0.12.2
    - torchvision==0.15.2 
    - geomstats==2.7.0
